const CONFIG = {
    app: {
        mergeWindowMinutes: 60,
        minSecondsToKeepTimer: 10,
        defaultNextFeedingHours: 4,
        defaultTheme: 'dark', // 'dark' or 'light'
        defaultTab: 'view-pecho', // 'view-pecho' or 'view-biberon'
        defaultLang: 'es'
    },
    alarm: {
        frequencyHz: 800,
        repeatIntervalMs: 2000
    },
    storage: {
        historyKey: 'babyLogHistory',
        stateKey: 'babyLogCurrentState',
        settingsKey: 'babyLogSettings'
    }
};

const TRANSLATIONS = {
    es: {
        tab_pecho: "Pecho",
        tab_biberon: "Biberón",
        tab_history: "Historial",
        tab_settings: "Ajustes",
        breast_left: "Izquierdo",
        breast_right: "Derecho",
        time: "Tiempo",
        hour: "Hora",
        amount: "Cantidad",
        next_feeding: "Próxima toma:",
        diaper_change: "Cambio de pañal",
        register_btn: "REGISTRAR",
        registered: "¡REGISTRADO!",
        settings_title: "Ajustes",
        settings_lang: "Idioma",
        settings_theme: "Tema Claro",
        settings_default_tab: "Pestaña al abrir",
        settings_report: "Reportar un error",
        empty_history: "No hay registros guardados."
    },
    en: {
        tab_pecho: "Nursing",
        tab_biberon: "Bottle",
        tab_history: "History",
        tab_settings: "Settings",
        breast_left: "Left",
        breast_right: "Right",
        time: "Time",
        hour: "Time",
        amount: "Amount",
        next_feeding: "Next feed:",
        diaper_change: "Diaper change",
        register_btn: "SAVE",
        registered: "SAVED!",
        settings_title: "Settings",
        settings_lang: "Language",
        settings_theme: "Light Theme",
        settings_default_tab: "Default Tab",
        settings_report: "Report a bug",
        empty_history: "No records saved."
    },
    zh: {
        tab_pecho: "母乳喂养",
        tab_biberon: "奶瓶",
        tab_history: "历史",
        tab_settings: "设置",
        breast_left: "左侧",
        breast_right: "右侧",
        time: "持续时间",
        hour: "时间",
        amount: "数量",
        next_feeding: "下次喂奶:",
        diaper_change: "换尿布",
        register_btn: "保存",
        registered: "已保存！",
        settings_title: "设置",
        settings_lang: "语言",
        settings_theme: "浅色主题",
        settings_default_tab: "默认标签页",
        settings_report: "报告错误",
        empty_history: "没有保存的记录。"
    },
    hi: {
        tab_pecho: "स्तनपान",
        tab_biberon: "बोतल",
        tab_history: "इतिहास",
        tab_settings: "सेटिंग्स",
        breast_left: "बायां",
        breast_right: "दायां",
        time: "समय",
        hour: "समय",
        amount: "मात्रा",
        next_feeding: "अगला आहार:",
        diaper_change: "डायपर बदलें",
        register_btn: "सहेजें",
        registered: "सहेजा गया!",
        settings_title: "सेटिंग्स",
        settings_lang: "भाषा",
        settings_theme: "लाइट थीम",
        settings_default_tab: "डिफ़ॉल्ट टैब",
        settings_report: "बग रिपोर्ट करें",
        empty_history: "कोई रिकॉर्ड नहीं।"
    },
    ar: {
        tab_pecho: "رضاعة طبيعية",
        tab_biberon: "زجاجة",
        tab_history: "السجل",
        tab_settings: "الإعدادات",
        breast_left: "اليسار",
        breast_right: "اليمين",
        time: "المدة",
        hour: "الوقت",
        amount: "الكمية",
        next_feeding: "الرضعة القادمة:",
        diaper_change: "تغيير الحفاض",
        register_btn: "حفظ",
        registered: "تم الحفظ!",
        settings_title: "الإعدادات",
        settings_lang: "اللغة",
        settings_theme: "الوضع الفاتح",
        settings_default_tab: "علامة التبويب الافتراضية",
        settings_report: "الإبلاغ عن خطأ",
        empty_history: "لا توجد سجلات."
    },
    fr: {
        tab_pecho: "Allaitement",
        tab_biberon: "Biberon",
        tab_history: "Historique",
        tab_settings: "Paramètres",
        breast_left: "Gauche",
        breast_right: "Droit",
        time: "Durée",
        hour: "Heure",
        amount: "Quantité",
        next_feeding: "Prochain repas:",
        diaper_change: "Couche",
        register_btn: "ENREGISTRER",
        registered: "ENREGISTRÉ !",
        settings_title: "Paramètres",
        settings_lang: "Langue",
        settings_theme: "Thème Clair",
        settings_default_tab: "Onglet par défaut",
        settings_report: "Signaler un bug",
        empty_history: "Aucun enregistrement."
    },
    ru: {
        tab_pecho: "Грудь",
        tab_biberon: "Бутылочка",
        tab_history: "История",
        tab_settings: "Настройки",
        breast_left: "Левая",
        breast_right: "Правая",
        time: "Время",
        hour: "Часы",
        amount: "Объем",
        next_feeding: "След. кормление:",
        diaper_change: "Смена подгузника",
        register_btn: "СОХРАНИТЬ",
        registered: "СОХРАНЕНО!",
        settings_title: "Настройки",
        settings_lang: "Язык",
        settings_theme: "Светлая тема",
        settings_default_tab: "Вкладка по умолчанию",
        settings_report: "Сообщить об ошибке",
        empty_history: "Нет записей."
    },
    pt: {
        tab_pecho: "Peito",
        tab_biberon: "Mamadeira",
        tab_history: "Histórico",
        tab_settings: "Ajustes",
        breast_left: "Esquerdo",
        breast_right: "Direito",
        time: "Tempo",
        hour: "Hora",
        amount: "Quantidade",
        next_feeding: "Próxima mamada:",
        diaper_change: "Troca de fralda",
        register_btn: "SALVAR",
        registered: "SALVO!",
        settings_title: "Ajustes",
        settings_lang: "Idioma",
        settings_theme: "Tema Claro",
        settings_default_tab: "Aba Padrão",
        settings_report: "Reportar erro",
        empty_history: "Nenhum registro."
    },
    de: {
        tab_pecho: "Stillen",
        tab_biberon: "Flasche",
        tab_history: "Verlauf",
        tab_settings: "Einstellungen",
        breast_left: "Links",
        breast_right: "Rechts",
        time: "Dauer",
        hour: "Uhrzeit",
        amount: "Menge",
        next_feeding: "Nächste Mahlzeit:",
        diaper_change: "Windel wechseln",
        register_btn: "SPEICHERN",
        registered: "GESPEICHERT!",
        settings_title: "Einstellungen",
        settings_lang: "Sprache",
        settings_theme: "Helles Design",
        settings_default_tab: "Standard-Tab",
        settings_report: "Fehler melden",
        empty_history: "Keine Einträge."
    },
    ja: {
        tab_pecho: "授乳",
        tab_biberon: "哺乳瓶",
        tab_history: "履歴",
        tab_settings: "設定",
        breast_left: "左",
        breast_right: "右",
        time: "時間",
        hour: "時刻",
        amount: "量",
        next_feeding: "次の授乳:",
        diaper_change: "おむつ交換",
        register_btn: "保存",
        registered: "保存しました！",
        settings_title: "設定",
        settings_lang: "言語",
        settings_theme: "ライトテーマ",
        settings_default_tab: "デフォルトタブ",
        settings_report: "バグを報告",
        empty_history: "記録がありません。"
    },
    it: {
        tab_pecho: "Seno",
        tab_biberon: "Biberon",
        tab_history: "Cronologia",
        tab_settings: "Impostazioni",
        breast_left: "Sinistro",
        breast_right: "Destro",
        time: "Durata",
        hour: "Ora",
        amount: "Quantità",
        next_feeding: "Prossima poppata:",
        diaper_change: "Cambio pannolino",
        register_btn: "SALVA",
        registered: "SALVATO!",
        settings_title: "Impostazioni",
        settings_lang: "Lingua",
        settings_theme: "Tema Chiaro",
        settings_default_tab: "Scheda predefinita",
        settings_report: "Segnala un bug",
        empty_history: "Nessun record."
    }
};
